export const tipsProducts = [
  {
    id: 0,
    img: "images/Mask Group.png",
    date: "January 15, 2019 - Travel Tips",
    textCard: "Going to the wild? What should you pack?",
    locationImg: "/images/Marker.png",
    location: "North Pole",
    commentImg: "/images/Communication.png",
    comment: "12 Comment",
    starImg: "/images/Star.png",
    star: "4.8 of 5",
  },
  {
    id: 1,
    img: "images/african-american-man-listening-music-with-vintage-boombox-stereo-outdoor-beach-summer-lifestyle-travel-party-concept-focus-face 1.png",
    date: "January 15, 2019 - Travel Tips",
    textCard: "Summer Vibes... Where to spend the energy.",
    locationImg: "/images/Marker.png",
    location: "North Pole",
    commentImg: "/images/Communication.png",
    comment: "12 Comment",
    starImg: "/images/Star.png",
    star: "4.8 of 5",
  },
  {
    id: 2,
    img: "images/jc-gellidon-Khqmo4T-rs0-unsplash 1.png",
    date: "January 15, 2019 - Travel Tips",
    textCard: "Smartet cites and how to enjoy them.",
    locationImg: "/images/Marker.png",
    location: "North Pole",
    commentImg: "/images/Communication.png",
    comment: "12 Comment",
    starImg: "/images/Star.png",
    star: "4.8 of 5",
  },
  {
    id: 3,
    img: "images/emile-seguin-R9OueKOtGGU-unsplash 1.png",
    date: "January 15, 2019 - Travel Tips",
    textCard: "Going to the wild? What should you pack?",
    locationImg: "/images/Marker.png",
    location: "North Pole",
    commentImg: "/images/Communication.png",
    comment: "12 Comment",
    starImg: "/images/Star.png",
    star: "4.8 of 5",
  },
  {
    id: 4,
    img: "images/emile-seguin-R9OueKOtGGU-unsplash 1 (1).png",
    date: "January 15, 2019 - Travel Tips",
    textCard: "Foods to try when you Visit Australia.",
    locationImg: "/images/Marker.png",
    location: "North Pole",
    commentImg: "/images/Communication.png",
    comment: "12 Comment",
    starImg: "/images/Star.png",
    star: "4.8 of 5",
  },
  {
    id: 5,
    img: "images/emile-seguin-R9OueKOtGGU-unsplash 1 (2).png",
    date: "January 15, 2019 - Travel Tips",
    textCard: "Beaches And how to enjoy them the most.",
    locationImg: "/images/Marker.png",
    location: "North Pole",
    commentImg: "/images/Communication.png",
    comment: "12 Comment",
    starImg: "/images/Star.png",
    star: "4.8 of 5",
  },
  {
    id: 6,
    img: "images/emile-seguin-R9OueKOtGGU-unsplash 1 (3).png",
    date: "January 15, 2019 - Travel Tips",
    textCard: "Road Trip 101 Things you need to know",
    locationImg: "/images/Marker.png",
    location: "North Pole",
    commentImg: "/images/Communication.png",
    comment: "12 Comment",
    starImg: "/images/Star.png",
    star: "4.8 of 5",
  },
  {
    id: 7,
    img: "images/emile-seguin-R9OueKOtGGU-unsplash 1 (4).png",
    date: "January 15, 2019 - Travel Tips",
    textCard: "Water front precautions to take during travels",
    locationImg: "/images/Marker.png",
    location: "North Pole",
    commentImg: "/images/Communication.png",
    comment: "12 Comment",
    starImg: "/images/Star.png",
    star: "4.8 of 5",
  },
  {
    id: 8,
    img: "images/emile-seguin-R9OueKOtGGU-unsplash 1 (5).png",
    date: "January 15, 2019 - Travel Tips",
    textCard: "Going to the Extreme -The Northern Pole",
    locationImg: "/images/Marker.png",
    location: "North Pole",
    commentImg: "/images/Communication.png",
    comment: "12 Comment",
    starImg: "/images/Star.png",
    star: "4.8 of 5",
  },
];
